branches:
  - master

build:
  ssl-key:
    image: alpine:3.2
    commands:
      - echo $SSLKEY > eckey.b64
      - cat eckey.b64
      - base64 -w 0 -d eckey.b64 > ec.key
    environment:
      - SSLKEY=$$SSLKEY

publish:
  docker:
    registry: registry.engagementcoach.com.au
    username: ecuser
    password: $$DOCKER_PASSWORD
    email: "admin@engagement.coach"
    repo: registry.engagementcoach.com.au/elk-docker
    file: Dockerfile-test
    tag:
      - latest
      #- "1.$$BUILD_NUMBER.0"
      #- $$COMMIT
    when:
      branch: master
      event: push

#notify:
#  slack:
#    webhook_url: https://hooks.slack.com/services/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
#    channel: drone-io
#    username: drone
