branches:
  - master

build:
  ssl-key:
    image: alpine:3.2
    commands:
      - echo $SSLKEY > ecb64.key
      - base64 -d ecb64.key > ec.key
      - echo $SSLCRT > ecb64.crt
      - base64 -d ecb64.crt > ec.crt
    environment:
      - SSLKEY=$$SSLKEY
      - SSLCRT=$$SSLCRT
    when:
      branch: master
      event: push

publish:
  docker:
    registry: registry.engagementcoach.com.au
    username: ecuser
    password: $$DOCKER_PASSWORD
    email: "admin@engagement.coach"
    repo: registry.engagementcoach.com.au/elk-docker
    file: Dockerfile-ec
    tag:
      - latest
      #- "1.$$BUILD_NUMBER.0"
      #- $$COMMIT
    when:
      branch: master
      event: push

#notify:
#  slack:
#    webhook_url: https://hooks.slack.com/services/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
#    channel: drone-io
#    username: drone
