branches:
  - master

build:
  ember-staging:
    image: alpine:3.2
    commands:
      - echo $SSLKEY > eckey.key
      - cat eckey.key
    environment:
      - SSLKEY=$$SSLKEY

#notify:
#  slack:
#    webhook_url: https://hooks.slack.com/services/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
#    channel: drone-io
#    username: drone
