# Dockerfile for ELK stack
# Elasticsearch 2.2.0, Logstash 2.2.0, Kibana 4.4.0

# Build with:
# docker build -t <repo-user>/elk .

# Run with:
# docker run -p 5601:5601 -p 9200:9200 -p 5000:5000 -it --name elk <repo-user>/elk

FROM phusion/baseimage
MAINTAINER Sebastien Pujadas http://pujadas.net
ENV REFRESHED_AT 2016-02-03

###############################################################################
#                                INSTALLATION
###############################################################################

RUN echo $SSLKEY
RUN echo $SSLCRT